import { createHash } from "node:crypto";
import type { KnowledgeArticle } from "../domain.js";
import type { ProjectedResource, Representation, ResourceKey } from "./types.js";
export const REPRESENTATION_VERSION = 1;
export const ARTICLE_SECTION_BODY_LIMIT = 4_000;
export const normalizeText = (text: string): string => text.normalize("NFC").replace(/\r\n?/g, "\n").trim();
export const hashText = (text: string): string => createHash("sha256").update(text, "utf8").digest("hex");
const unsafeCaseText = /(?:\b(?:raw\s+)?(?:system|developer|user)\s+(?:prompt|message|instructions?)\b|\braw\s+prompt\b|\b(?:hidden|chain[- ]of[- ]thought|reasoning)\b|\b(?:api[-_]?key|access[-_]?token|secret|password)\s*[=:]\s*\S+|\bsk-[a-z0-9_-]+\b|\b(?:[a-z]:[\\/]|\\\\)|(?:^|\s)[~\/][^\s]*|\b(?:model|provider)\s+(?:payload|response)\b|^\s*[\[{]|https?:\/\/[^\s/@]+:[^\s/@]+)/i;
export function safeCaseText(text: string, identifiers: readonly string[]): string | undefined { let value = normalizeText(text); for (const identifier of identifiers) value = value.replaceAll(identifier, ""); value = normalizeText(value.replace(/\s{2,}/g, " ")); return value.length > 0 && !unsafeCaseText.test(value) ? value : undefined; }
function splitLongText(text: string): readonly string[] { if (text.length <= ARTICLE_SECTION_BODY_LIMIT) return [text]; const result: string[] = []; let remaining = text; while (remaining.length > ARTICLE_SECTION_BODY_LIMIT) { const boundary = remaining.lastIndexOf(" ", ARTICLE_SECTION_BODY_LIMIT); const index = boundary > 0 ? boundary : ARTICLE_SECTION_BODY_LIMIT; result.push(remaining.slice(0, index).trim()); remaining = remaining.slice(index).trim(); } if (remaining) result.push(remaining); return result; }
function splitBody(body: string): readonly { heading?: string; text: string }[] { const sections: { heading?: string; text: string }[] = []; let heading: string | undefined; let current: string[] = []; const flush = () => { const text = normalizeText(current.join("\n")); if (text) sections.push({ heading, text }); current = []; }; for (const line of normalizeText(body).split("\n")) { const match = /^(#{1,6})\s+(.+?)\s*#*\s*$/.exec(line); if (match) { flush(); heading = normalizeText(match[2]!); } else current.push(line); } flush(); return sections.flatMap((section) => splitLongText(section.text).map((text) => ({ heading: section.heading, text }))); }
export function projectArticle(article: KnowledgeArticle): ProjectedResource { const key = `knowledge-article:${article.id}` as ResourceKey; const tags = [...article.tags].map(normalizeText).sort(); const title = normalizeText(article.title); const representations: Representation[] = splitBody(article.body).map(({ heading, text }, ordinal) => { const semanticText = normalizeText([title, heading, text].filter(Boolean).join("\n\n")); const lexicalText = normalizeText([title, heading, tags.join(" "), text].filter(Boolean).join("\n")); const contentHash = hashText(JSON.stringify({ version: REPRESENTATION_VERSION, key, ordinal, title, heading, tags, text })); return { id: `${key}:section:${ordinal}`, resourceKey: key, kind: "section", ordinal, title, ...(heading ? { heading } : {}), keywords: tags, lexicalText, semanticText, contentHash }; }); const contentHash = hashText(JSON.stringify({ version: REPRESENTATION_VERSION, key, title, tags, representations: representations.map(({ id, contentHash }) => ({ id, contentHash })) })); return { resource: { key, type: "knowledge-article", sourceId: article.id, contentHash, family: "article", linkedResourceKeys: [] }, representations }; }
